FINGER_TIPS: dict[str, int] = {
    'thumb': 4,
    'index': 8,
    'middle': 12,
    'ring': 16,
    'pinky': 20,
}

FRAME_WIDTH = 640
FRAME_HEIGHT = 480

SCALE_MIN = 1.0
SCALE_MAX = 3.0
SCALE_STEP = 0.1
DEFAULT_SCALE = 1.5

MOUSE_SMOOTHING = 7
DEAD_ZONE_MARGIN = 100

SCROLL_DECAY = 0.3
SCROLL_AMOUNT = 0.7
SCROLL_VELOCITY_STEP = 2

COOLDOWN_FRAMES = 15
QUEUE_MAXSIZE = 3

DEFAULT_CAMERA_ID = 0
